spring.application.name=backend

server.port=8080
spring.profiles.active=local

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRATION_MS}

verification.token.expiration.ms=${VERIFICATION_TOKEN_EXPIRATION_MS}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

frontend.url=${FRONTEND_BASE_URL}